# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Data Science for Economists
description:      'Teaching tools for research computing with an economics focus.'
url:              http://potterzot.com/semester-research-computing-economics
baseurl:          /semester-research-computing-economics
email:            potterzot@gmail.com
feedbackurl:      https://goo.gl/forms/cqhZsQrURtkTipIa2
author:
  name:           'Nicholas Potter'
  url:            https://twitter.com/potterzot

github:
  repo:           https://github.com/potterzot/semester-research-computing-economics
  #               Be sure the 'Issues' feature is activated in 'Settings'

theme: jekyll-theme-minimal
